# Site settings
title: Brittany McCall, VA
email: brittany@mccallconsulting.tech
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
#baseurl: "#" # the subpath of your site, e.g. /blog/
url: "http://brittany.mccallconsulting.tech/" # the base hostname & protocol for your site
#url: "" # the base hostname & protocol for your site

twitter_username: none
github_username: BrittLeigh

# Build settings
markdown: kramdown
